str="EleCtRonIcs EngiNeeRing"
print(type(str))
print(id(str))
print(str.upper())
print(str.lower())
print(str.capitalize())
print(str.title())
print(str.swapcase())
print(str.isalpha())
print(str.isdigit())
print(str.isupper())
print(str.islower())
print(str.startswith('E'))
print(str.endswith('g'))
print(str.count('R'))
